### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.fusesource.jansi.WindowsAnsiOutputStream thrown on Windows

### ISSUE THREAD

**Issue by Bohtvaroh** [spray/sbt-revolver#36]
Can't make the plugin work on Windows. On `re-start` I get:

`java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path]
[ERROR] java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.WindowsAnsiOutputStream`

Full stacktrace: http://pastebin.com/jgeRDnam

I tried deleting ~.ivy2, ~.sbt but with no luck. On sbt start `.sbt\boot\other\org.fusesource.jansi\jansi\1.11\jansi-1.11.jar` file is created.

Same config works okay on OSX.

**Comment by omidb** [comment]
I have the same problem:
```
sharedProjectJVM[ERROR] Uncaught error from thread [SPA-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[SPA]
sharedProjectJVM[ERROR] java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.WindowsAnsiOutputStream
sharedProjectJVM[ERROR]         at java.lang.Class.forName0(Native Method)
sharedProjectJVM[ERROR]         at java.lang.Class.forName(Class.java:260)
sharedProjectJVM [ERROR] [07/06/2015 18:15:57.950] [SPA-akka.actor.default-dispatcher-2] [ActorSystem(SPA)] Uncaught error from thread [SPA-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-erro
r' is enabled
sharedProjectJVM java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.WindowsAnsiOutputStream
sharedProjectJVM        at java.lang.Class.forName0(Native Method)
sharedProjectJVM        at java.lang.Class.forName(Class.java:260)
sharedProjectJVM        at org.apache.logging.log4j.core.util.Loader.loadClassWithDefaultClassLoader(Loader.java:272)
sharedProjectJVM        at org.apache.logging.log4j.core.util.Loader.loadClass(Loader.java:267)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.util.Loader.loadClassWithDefaultClassLoader(Loader.java:272)
sharedProjectJVM        at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:125)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.util.Loader.loadClass(Loader.java:267)
sharedProjectJVM        at org.apache.logging.log4j.core.appender.ConsoleAppender.getManager(ConsoleAppender.java:104)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:125)
sharedProjectJVM        at org.apache.logging.log4j.core.appender.ConsoleAppender.createAppender(ConsoleAppender.java:99)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.appender.ConsoleAppender.getManager(ConsoleAppender.java:104)
sharedProjectJVM        at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:60)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.appender.ConsoleAppender.createAppender(ConsoleAppender.java:99)
sharedProjectJVM        at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:72)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:60)
sharedProjectJVM        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:72)
sharedProjectJVM        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:113)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
sharedProjectJVM        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:80)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:113)
sharedProjectJVM        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:82)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:80)
sharedProjectJVM        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:37)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:82)
sharedProjectJVM        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:474)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:37)
sharedProjectJVM        at reactivemongo.utils.LazyLogger$.apply(utils.scala:55)
sharedProjectJVM[ERROR]         at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:474)
sharedProjectJVM        at reactivemongo.api.MongoDriver$.<init>(api.scala:642)
sharedProjectJVM[ERROR]         at reactivemongo.utils.LazyLogger$.apply(utils.scala:55)
sharedProjectJVM        at reactivemongo.api.MongoDriver$.<clinit>(api.scala)
sharedProjectJVM[ERROR]         at reactivemongo.api.MongoDriver$.<init>(api.scala:642)
sharedProjectJVM        at rocnlpui.server.MongoManager$.driver$lzycompute(MongoManager.scala:21)
sharedProjectJVM[ERROR]         at reactivemongo.api.MongoDriver$.<clinit>(api.scala)
sharedProjectJVM        at rocnlpui.server.MongoManager$.driver(MongoManager.scala:21)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.driver$lzycompute(MongoManager.scala:21)
sharedProjectJVM        at rocnlpui.server.MongoManager$.connection$lzycompute(MongoManager.scala:22)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.driver(MongoManager.scala:21)
sharedProjectJVM        at rocnlpui.server.MongoManager$.connection(MongoManager.scala:22)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.connection$lzycompute(MongoManager.scala:22)
sharedProjectJVM        at rocnlpui.server.MongoManager$.db$lzycompute(MongoManager.scala:23)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.connection(MongoManager.scala:22)
sharedProjectJVM        at rocnlpui.server.MongoManager$.db(MongoManager.scala:23)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.db$lzycompute(MongoManager.scala:23)
sharedProjectJVM        at rocnlpui.server.MongoManager$.annotationTasks$lzycompute(MongoManager.scala:25)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.db(MongoManager.scala:23)
sharedProjectJVM        at rocnlpui.server.MongoManager$.annotationTasks(MongoManager.scala:25)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.annotationTasks$lzycompute(MongoManager.scala:25)
sharedProjectJVM        at rocnlpui.server.MongoManager$.getAnnotationAssignmentHistory(MongoManager.scala:35)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.annotationTasks(MongoManager.scala:25)
sharedProjectJVM        at rocnlpui.server.TaskManager$.AddNewAnnotations(TaskManager.scala:17)
sharedProjectJVM        at rocnlpui.server.ApiService.parse(ApiService.scala:76)
sharedProjectJVM[ERROR]         at rocnlpui.server.MongoManager$.getAnnotationAssignmentHistory(MongoManager.scala:35)
sharedProjectJVM        at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$1.applyOrElse(MainApp.scala:59)
sharedProjectJVM[ERROR]         at rocnlpui.server.TaskManager$.AddNewAnnotations(TaskManager.scala:17)
sharedProjectJVM        at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$1.applyOrElse(MainApp.scala:59)
sharedProjectJVM[ERROR]         at rocnlpui.server.ApiService.parse(ApiService.scala:76)
sharedProjectJVM        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
sharedProjectJVM[ERROR]         at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$1.applyOrElse(MainApp.scala:59)
sharedProjectJVM[ERROR]         at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$1.applyOrElse(MainApp.scala:59)
sharedProjectJVM        at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5.apply(MainApp.scala:59)
sharedProjectJVM[ERROR]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
sharedProjectJVM        at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5.apply(MainApp.scala:57)
sharedProjectJVM[ERROR]         at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5.apply(MainApp.scala:59)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at rocnlpui.server.MainApp$$anonfun$main$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5.apply(MainApp.scala:57)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
sharedProjectJVM        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
sharedProjectJVM[ERROR]         at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
sharedProjectJVM        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
sharedProjectJVM        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
sharedProjectJVM        at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.RequestContext.reject(RequestContext.scala:202)
sharedProjectJVM        at spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
sharedProjectJVM        at spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM[ERROR]         at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
sharedProjectJVM        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
sharedProjectJVM[ERROR]         at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
sharedProjectJVM[ERROR]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
sharedProjectJVM        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
sharedProjectJVM[ERROR]         at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM[ERROR]         at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
sharedProjectJVM        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
sharedProjectJVM        at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
sharedProjectJVM[ERROR]         at spray.routing.RequestContext.reject(RequestContext.scala:202)
sharedProjectJVM        at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
sharedProjectJVM[ERROR]         at spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
sharedProjectJVM        at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
sharedProjectJVM[ERROR]         at spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
sharedProjectJVM        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at spray.routing.SimpleRoutingApp$$anonfun$1$$anon$1.aroundReceive(SimpleRoutingApp.scala:54)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
sharedProjectJVM        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
sharedProjectJVM[ERROR]         at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
sharedProjectJVM        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
sharedProjectJVM        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
sharedProjectJVM        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
sharedProjectJVM[ERROR]         at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
sharedProjectJVM        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
sharedProjectJVM        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
sharedProjectJVM        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
sharedProjectJVM        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
sharedProjectJVM[ERROR]         at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
sharedProjectJVM
sharedProjectJVM[ERROR]         at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
sharedProjectJVM[ERROR]         at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
sharedProjectJVM[ERROR]         at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
sharedProjectJVM[ERROR]         at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
sharedProjectJVM[ERROR]         at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
sharedProjectJVM[ERROR]         at spray.routing.SimpleRoutingApp$$anonfun$1$$anon$1.aroundReceive(SimpleRoutingApp.scala:54)
sharedProjectJVM[ERROR]         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
sharedProjectJVM[ERROR]         at akka.actor.ActorCell.invoke(ActorCell.scala:487)
sharedProjectJVM[ERROR]         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
sharedProjectJVM[ERROR]         at akka.dispatch.Mailbox.run(Mailbox.scala:221)
sharedProjectJVM[ERROR]         at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
sharedProjectJVM[ERROR]         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
sharedProjectJVM[ERROR]         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
sharedProjectJVM[ERROR]         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
sharedProjectJVM[ERROR]         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
sharedProjectJVM ... finished with exit code -1
```

**Comment by jrudolph** [comment]
@omidb sorry for not answering sooner. Have you checked if the same happens with `fork in run := true`? We do not attempt to fix problems that also occur with forked runs which we just try to augment with extra functionality. If there's still a problem with this it needs to be fixed in sbt itself.

I'm closing this for now. If you can demonstrate that your problem happens only with sbt-revolver but not with `fork in run := true` please reopen.
